### ISSUE TITLE
[Question] Is there an easy way of feed the MediaLive with RTSP stream?

### ISSUE THREAD

**Issue by amadeu01** [awslabs/live-stream-on-aws#16]
I have a stream in RTSP and I would like to feed the MediaLive with this RTSP link, but I couldn't find a way to do this.

**Comment by tomnight** [comment]
I don't think RTSP is currently supported an input for MediaLive, the support inputs are listed here:

https://docs.aws.amazon.com/medialive/latest/ug/inputs-supported-containers.html
