### ISSUE TITLE
Enconding profiles do not support new attribute QvbrQualityLevel for media live

### ISSUE THREAD

**Issue by markitodelacruz** [awslabs/live-stream-on-aws#2]
Hi there. 
When editing source/custom-resource-py/encoding-profiles/medialive-1080p.json in order to add the new parameter QvbrQualityLevel to VideoDescription node, this script will crash at the moment of creation at CloudFormation with the following error:

Unknown parameter in EncoderSettings.VideoDescriptions[0].CodecSettings.H264Settings: "QvbrQualityLevel", must be one of: AdaptiveQuantization, AfdSignaling, Bitrate, BufFillPct, BufSize, ColorMetadata, EntropyEncoding, FixedAfd, FlickerAq, FramerateControl, FramerateDenominator, FramerateNumerator, GopBReference, GopClosedCadence, GopNumBFrames, GopSize, GopSizeUnits, Level, LookAheadRateControl

**Comment by tomnight** [comment]
Hi there,
Could you post the json file to this tread and I will try and replicate the issue? 
Thanks
