### ISSUE TITLE
Input Security Groups not deleted by Delete section

### ISSUE THREAD

**Issue by jagoodhand** [awslabs/live-stream-on-aws#3]
https://github.com/awslabs/live-stream-on-aws/blob/e691332b659652ccf8aff8dddf2e4fd0e833551c/source/custom-resource-py/lambda.py#L81-L98

Does not include code to delete Input Security Groups so these build up as orphan resources in the account as the stack is created / deleted.

**Comment by tomnight** [comment]
Hi and thanks for the feedback.
You are correct deleting the Security Group is currently not part of the custom resource, we will look this add this as a feature in the next release.

**Comment by shsenior** [comment]
v2.2.1 Update.
