### ISSUE TITLE
Unable to use demo player with RTMP_PUSH configuration

### ISSUE THREAD

**Issue by daviseford** [awslabs/live-stream-on-aws#4]
Hey guys,

First of all, I previously installed the template using the URL_PULL config and it worked flawlessly, so thanks!

My problem now: I set up the stack using the RTMP_PUSH config, setting 0.0.0.0/0 as the incoming CIDR block, and the stack deployed successfully.

I open the demo player (Chrome or Firefox, both get the error) to check my RTMP stream.. and I get this error:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://abcde.cloudfront.net/out/v1/abcde/index.m3u8. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).[Learn More]

VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. 
Object { code: 4, message: "The media could not be loaded, either because the server or network failed or because the format is not supported." }
```

Please let me know if you need any other information.

**Comment by tomnight** [comment]
the latest release for the solution has been tested with every input type spo could you please try the latest release.

If you still seeing an issue please check to see if you can preview the stream playback in the mediapackge console.

navigate to teh Mediapackage console > select the channel created by the solution > select the preview option for each of the MediaPackage Endpoints. 

If you not seeing the content here either I would suggest you review the documentation and double check your RTMP configuration.

https://docs.aws.amazon.com/medialive/latest/ug/rtmp-push-input.html

Hope this helps
