### ISSUE TITLE
Update of template fails

### ISSUE THREAD

**Issue by andreasunterhuber** [awslabs/live-stream-on-aws#8]
Update of stack properties fails, just editing the URL fails with an error:
`CustomResource attribute error: Vendor response doesn't contain Id key in object arn:aws:cloudformation::XXXX ...` 
 (NodeJS env)

**Comment by tomnight** [comment]
Thanks for reaching out. The custom resource that is used by CloudFormation dosen't support the update actions. I will add this as a feature request.
